### ISSUE TITLE
Incomplete Implementation of scan_usb_device

### ISSUE THREAD

**Issue by Abhinavexists** [ShreyaTejan/USB-Forensics-Tool#1]
The scan_usb_drive function is currently incomplete and lacks the necessary logic to scan files on USB drives for specific patterns. This results in no file content being analyzed.

**Comment by ShreyaTejan** [comment]
Hi! This is the new updated code for the scan_usb_function with the file link- https://github.com/ShreyaTejan/USB-Forensics-Tool/blob/main/git_issue%20USB.py
