### ISSUE TITLE
Logging Implementation required 

### ISSUE THREAD

**Issue by Abhinavexists** [ShreyaTejan/USB-Forensics-Tool#2]
The current implementation of code lacks the implementation of logging which is required to identify particular issues and crashes .

**Comment by ShreyaTejan** [comment]
I have Initialized logging to usb_forensics.log with level set to INFO and added Log Statements for:
Start and completion of each function.
Critical operations, such as scanning drives and reading logs.
Errors, warnings, and significant findings, like unauthorized device detection and threats in files.
 
This is the link where I have made the changes: https://github.com/ShreyaTejan/USB-Forensics-Tool/blob/main/logging%20for%20USB%20analysis.py
